#!/bin/sh /etc/rc.common

START=79
STOP=11

EXTRA_COMMANDS="backup restore"
EXTRA_HELP="    backup  backup current rrd database"

RRD_DIR="tmp/rrd"
BACKUP_DIR="/root/statistics_backup"
BACKUP_FILE="rrdbackup.tar.gz"

backup() {
    [ ! -d "$RRD_DIR" ] && return 0

    local TMP_FILE
    TMP_FILE="$(mktemp)"

    echo "Backing up RRD to $BACKUP_DIR/$BACKUP_FILE"
    mkdir -p "$BACKUP_DIR"
    tar -czf "$TMP_FILE" -C / "$RRD_DIR"

    mv "$TMP_FILE" "$BACKUP_DIR/$BACKUP_FILE"
}

restore() {
    if [ -f "$BACKUP_DIR/$BACKUP_FILE" ]; then
        echo "Restoring RRD from $BACKUP_DIR/$BACKUP_FILE"
        mkdir -p "$(dirname "$RRD_DIR")"
        tar -xzf "$BACKUP_DIR/$BACKUP_FILE" -C /
    fi
}

start() {
    restore
}

stop() {
    backup
}
